### ISSUE TITLE
智学网教师端用默认密码111111登录提示需修改密码

### ISSUE THREAD

**Issue by oneadminn** [xX7912Xx/zhixue#1]

**Comment by xX7912Xx** [comment]
是从网页上登录还是..?
如果是从网页上登录出现需要修改密码, 登录后可以直接进入
https://www.zhixue.com/htm-freshreport/#/schoolReportList/schoolReportListIndex
再点击上方的任意一个选项, 就可以跳过修改密码的环节了.

**Comment by oneadminn** [comment]
感谢，是网页登录，已经解决了
